# url: "" # https://...
# baseurl: ""
title: Hello WebWeb01
description: (V035-20190706) WebWeb01 with jekyll-theme-hacker
email: e@ma.il
show_downloads: false
google_analytics:

theme: jekyll-theme-hacker

# theme: jekyll-theme-dinky
# theme: jekyll-theme-merlot
# theme: jekyll-theme-midnight

# Fixing the "No GitHub API authentication could be found" ??
github:
   - is_project_page: false

#     [metadata]

sitevar: "Site Var"

defaults:
   -
      scope:
       path: ""
      values:
         layout: "default"
         title:  "TITLE"
         dummy:  "Dummy"

# paginate: 5
